/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "hid_msg.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(hid_msg_CtrlMessage, hid_msg_CtrlMessage, AUTO)


PB_BIND(hid_msg_PcMessage, hid_msg_PcMessage, AUTO)


PB_BIND(hid_msg_Nil, hid_msg_Nil, AUTO)


PB_BIND(hid_msg_Version, hid_msg_Version, AUTO)


PB_BIND(hid_msg_Eink, hid_msg_Eink, AUTO)


PB_BIND(hid_msg_knob, hid_msg_knob, AUTO)


PB_BIND(hid_msg_Utils, hid_msg_Utils, AUTO)


PB_BIND(hid_msg_knobPID, hid_msg_knobPID, AUTO)


PB_BIND(hid_msg_knobPID_Velocity, hid_msg_knobPID_Velocity, AUTO)


PB_BIND(hid_msg_knobPID_Angle, hid_msg_knobPID_Angle, AUTO)





