//
// Created by 19254 on 2023/9/20.
//

#ifndef HELLOWORD_DYNAMIC_FW_STORAGE_COMPATIBLE_HPP
#define HELLOWORD_DYNAMIC_FW_STORAGE_COMPATIBLE_HPP

#include "os_define.hpp"




#endif //HELLOWORD_DYNAMIC_FW_STORAGE_COMPATIBLE_HPP
